Update setup-machines.yml

diff --git a/.github/workflows/setup-machines.yml b/.github/workflows/setup-machines.yml
--- a/.github/workflows/setup-machines.yml
+++ b/.github/workflows/setup-machines.yml
@@ -16,30 +16,30 @@ jobs:
         shell: bash
 
     steps:
-    - uses: actions/checkout@v2
-      with:
-        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+      - name: Checkout Git repository
+        uses: actions/checkout@v2
+        with:
+          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
-    - name: Setup fractal user
-      run: |
-        sudo useradd fractal || echo "fractal user already exists"
-        echo 'fractal:password1234567.' | sudo chpasswd && echo "Set password"
-        sudo mkhomedir_helper fractal
+      - name: Setup fractal user
+        run: |
+          sudo useradd fractal || echo "fractal user already exists"
+          echo 'fractal:password1234567.' | sudo chpasswd && echo "Set password"
+          sudo mkhomedir_helper fractal
+          echo $HOME
 
-        echo $HOME
-
-    - name: Run cloud-0.sh
-      run: ./cloud-0.sh
-      working-directory: linux
-      env:
+      - name: Run cloud-0.sh
+        run: ./cloud-0.sh
+        working-directory: linux
+        env:
           LOCAL: yes
           FRACTAL_GITHUB_ACTION: yes
           
-    - name: Run cloud-1.sh
-      run: ./cloud-1.sh
-      working-directory: linux
-      env:
+      - name: Run cloud-1.sh
+        run: ./cloud-1.sh
+        working-directory: linux
+        env:
           LOCAL: yes
           FRACTAL_GITHUB_ACTION: yes
 
@@ -52,23 +52,24 @@ jobs:
         shell: powershell
 
     steps:
-    - uses: actions/checkout@v2
-      with:
-        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+      - name: Checkout Git repository
+        uses: actions/checkout@v2
+        with:
+          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
-    - name: Create Fractal user
-      run: |
-        $pass = (ConvertTo-SecureString "password1234567." -AsPlainText -Force)
-        New-LocalUser -FullName "Fractal" -Name "Fractal" -Password $pass -Description "Fractal Account"
-        Add-LocalGroupMember -Group "Administrators" -Member "Fractal"
-        $credentials = New-Object System.Management.Automation.PSCredential "Fractal", $pass
-        Start-Process powershell.exe -Credential $credentials
+      - name: Create Fractal user
+        run: |
+          $pass = (ConvertTo-SecureString "password1234567." -AsPlainText -Force)
+          New-LocalUser -FullName "Fractal" -Name "Fractal" -Password $pass -Description "Fractal Account"
+          Add-LocalGroupMember -Group "Administrators" -Member "Fractal"
+          $credentials = New-Object System.Management.Automation.PSCredential "Fractal", $pass
+          Start-Process powershell.exe -Credential $credentials
 
-    - name: Run cloud.ps1
-      run: ./cloud.ps1
-      working-directory: windows
-      env:
+      - name: Run cloud.ps1
+        run: ./cloud.ps1
+        working-directory: windows
+        env:
           LOCAL: yes
           NO_UPDATE: yes
           QUIET: yes
